version: '3.0'

services: 
    main:
        container_name: main
        build: 
            context: .
        env_file: 
            - .env
        volumes: 
            - .:/app
            - /app/node_modules
        ports: 
            - ${PORT}:${PORT}
        depends_on: 
            - postgres
        restart: always